#!/usr/bin/env python3
"""Codegen: generate reviewedSegmentCodes.ts from reviewed_segment_codes.json.

Reads agent/config/reviewed_segment_codes.json (single source of truth) and
generates frontend/src/lib/reviewedCodes/reviewedSegmentCodes.ts.

Run:
    python3 scripts/codegen_reviewed_codes.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "agent" / "config" / "reviewed_segment_codes.json"
OUTPUT_PATH = (
    ROOT
    / "frontend"
    / "src"
    / "lib"
    / "reviewedCodes"
    / "reviewedSegmentCodes.ts"
)

HEADER = """\
// ---------------------------------------------------------------------------
// AUTO-GENERATED by scripts/codegen_reviewed_codes.py
// Source: agent/config/reviewed_segment_codes.json
// Do not edit by hand — run the codegen script to update.
//
// Frontend mirror of agent/config/reviewed_segment_codes.json.
// Single source of truth is the JSON manifest.
//
// Quote-only codes here do NOT feed into ReportLibrary (which uses the
// separate segmentCodeMap).  Use getQuoteCodes() / getReportCodes() from
// reviewedManifestAdapter to filter by dataUse.
// ---------------------------------------------------------------------------

import type { ManifestData } from "./reviewedManifestAdapter";

"""


def _ts_string(s: str) -> str:
    """JSON-encode a string for use as a TypeScript literal."""
    return json.dumps(s, ensure_ascii=False)


def _is_js_identifier(s: str) -> bool:
    """Return True when *s* can be used as an unquoted JS property key."""
    if not s:
        return False
    # JS identifiers: start with [a-zA-Z_$], followed by [a-zA-Z0-9_$]
    if not (s[0].isalpha() or s[0] in ("_", "$")):
        return False
    return all(c.isalnum() or c in ("_", "$") for c in s[1:])


def _ts_key(k: str) -> str:
    """Return *k* as a TypeScript object key (quoted only if necessary)."""
    if _is_js_identifier(k):
        return k
    return _ts_string(k)


def json_to_ts(obj, indent: int = 0) -> str:
    """Convert a JSON-compatible value to a TypeScript literal expression."""
    pad = " " * indent
    next_pad = " " * (indent + 2)

    if obj is None:
        return "null"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    if isinstance(obj, (int, float)):
        if isinstance(obj, float) and obj == int(obj):
            return str(int(obj))
        return json.dumps(obj)
    if isinstance(obj, str):
        return _ts_string(obj)
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = [f"{next_pad}{json_to_ts(v, indent + 2)}" for v in obj]
        return "[\n" + ",\n".join(items) + f",\n{pad}]"
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = [
            f"{next_pad}{_ts_key(k)}: {json_to_ts(v, indent + 2)}"
            for k, v in obj.items()
        ]
        return "{\n" + ",\n".join(items) + ",\n" + pad + "}"
    raise TypeError(f"Unsupported type: {type(obj)}")


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    # Remove $schema — not needed in the frontend mirror.
    manifest.pop("$schema", None)

    ts_literal = json_to_ts(manifest, indent=0)
    output = (
        HEADER
        + f"export const REVIEWED_SEGMENT_CODES = {ts_literal} as const satisfies ManifestData;\n"
    )

    # Only write if content actually changed (avoid unnecessary timestamps).
    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8") == output:
        print(f"✅  {OUTPUT_PATH} is already up-to-date")
        return

    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"✅  Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
